export default {
  APP_NAME: 'Dummy react app',
  APP_DOM_CONTAINER: 'react-view',
  ACTIONS: {
    REQUEST_LOGIN_AUTH: 'REQUEST_LOGIN_AUTH',
    RECEIVE_LOGIN_AUTH: 'RECEIVE_LOGIN_AUTH',
    ERROR_LOGIN_AUTH: 'ERROR_LOGIN_AUTH',
  }
}