export default {
  APP_NAME: 'Dummy react app',
  APP_DOM_CONTAINER: 'react-view',
  ACTIONS: {
    REQUEST_LOGIN_AUTH: 'REQUEST_LOGIN_AUTH',
    RECEIVE_LOGIN_AUTH: 'RECEIVE_LOGIN_AUTH',
    ERROR_LOGIN_AUTH: 'ERROR_LOGIN_AUTH',
    SUBMIT_RECIPE: 'SUBMIT_RECIPE',
    RECIPE_CREATED: 'RECIPE_CREATED',
    RECIPE_SUBMIT_ERROR: 'RECIPE_SUBMIT_ERROR',
    LOGOUT: 'LOGOUT',
    REGISTRATION_SENT: 'REGISTRATION_SENT',
    REGISTRATION_COMPLETED: 'REGISTRATION_COMPLETED',
    REGISTRATION_ERRORS: 'REGISTRATION_ERRORS'
  },
  MESSAGES: {
    recipeCreated: 'Your recipe was successfully created'
  }
}